export {NavBar} from "./NavBar"
export {Home} from "./Home"
export {SocialLinks} from "./SocialLinks"
export {About} from "./About"
export {Portfolio} from "./Portfolio"
export {Skill} from "./Skill"
export {Contact} from "./Contact"
export {Experience} from "./Experience"